server:
  port: 8080
# mybatis配置
mybatis:
  # sql语句打印在控制台上
  # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jmx.pojo
# 通用mapper配置
mapper:
  mappers: com.jmx.utils.MyMapper
  not-empty: false
  identity: MYSQL
# 分页设置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/easychat?characterEncoding=utf8&useSSL=false
    # hikari配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatabookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.0.4:22122
    - 192.168.0.4:22122